language: scala
sudo: false
jdk: oraclejdk8
script:
  - sbt scripted
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.isabelle
    - $HOME/.local/share/libisabelle
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
